[package]
name = "pic-x-storage"
description = "In-process implementation of the PIC-X storage contract."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
pic-x-core.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
